// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpwzmlbwrtbiznthucqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwd3ptbGJ3cnRiaXpudGh1Y3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTA1NzIsImV4cCI6MjA3MDg2NjU3Mn0.Lly-ahQ8CyxMgIv4Eqb58saLSO5PNpluiCF4rfnySXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});